project_name: hello
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: InfluxData <support@influxdata.com>
  description: InfluxDB
  homepage: https://github.com/influxdata/influxdb
  license: MIT
  formats:
  - deb
  - rpm
  - apk
